## 텐서 기본 실습

In [3]:
import torch
import torchvision

In [4]:
print("troch 버전 >> ", torch.__version__)
print("torchvision version >> ", torchvision.__version__)

troch 버전 >>  1.10.1
torchvision version >>  0.11.2


In [5]:
import numpy as np

#### 텐서 초기화하기 데이터로부터 직접 텐서를 생성할 수 있다. 데이터의 자료형은 자동으로 유추


In [8]:
# 1. torch 이용해서 만든 텐서
data = [[1,2], [3,4]]
print(type(data))
x_data = torch.tensor(data)
print(x_data)

# 2. Numpy -> torch tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

<class 'list'>
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


- torch.tensor()는 입력 텐서를 복사하여 새로운 텐서를 만든다. 이 함수는 항상 새로운 메모리를 할당하므로, 원본 데이터와의 메모리 공유가 이루어지지 않는다.
- torch.from_numpy() 함수는 numpy 배열을 pytorch 텐서로 변환할 때, 원본 데이터와의 메모리 공유를 유지한다.

In [10]:
x_ones = torch.ones_like(x_data)
print(f"ones Tensor : \n{x_ones}")
# torch.ones_like() 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 1로 채우면 된다.

x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data 속성을 덮어쓴다.
print(f"Random Tensor : \n{x_rand}")
# torch.rand_like() 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든 요소를 랜덤한 값으로 채운다. 그리고 타입 지정하면 그 타입으로 변경된다.
# 0과 1 사이의 랜덤한 값으로 초기화 되고 데이터 타입 유형은 dtype=torch.float 지정된다.

ones Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.9830, 0.9306],
        [0.3015, 0.6716]])


In [12]:
# 무작위 또는 상수 값을 사용하기
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("rand_tensor \n", rand_tensor)
print("ones_tensor \n", ones_tensor)
print("zeros_tensor \n", zeros_tensor)

# 유효 범위를 최소값 얼마부터 - 최대값 얼마까지
shape_temp = (5, 6)
min_val = 6
max_val = 10
rand_tensor_temp = torch.rand(shape_temp) * (max_val - min_val) + min_val
print(rand_tensor_temp)

rand_tensor 
 tensor([[0.2138, 0.4071, 0.0836],
        [0.0311, 0.1723, 0.7193]])
ones_tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[8.1709, 9.1610, 6.0789, 7.0330, 7.5559, 9.4307],
        [7.9741, 9.3196, 6.5208, 6.7950, 7.5188, 7.8547],
        [6.8034, 7.1655, 9.5533, 6.2348, 6.0133, 8.0222],
        [6.4175, 6.4517, 8.9776, 9.9812, 6.3154, 8.2574],
        [9.1376, 9.3100, 9.2110, 7.9392, 6.0611, 9.4936]])


shape = (2, 3, 4)는 3차원 텐서를 생성하는 것을 의미합니다. 이 텐서는 2개의 행렬로 구성되며, 각 행렬은 3행 4열의 형상을 갖습니다. 즉, (2, 3, 4)는 차원이 2개인 3행 4열의 텐서를 생성합니다.<br>
반면에 shape = (2, 3,)는 2차원 텐서를 생성하는 것을 의미합니다. 이 텐서는 2개의 행벡터로 구성되며, 각 행벡터는 3개의 요소를 갖습니다. 즉, (2, 3,)는 2행 3열의 텐서를 생성합니다.

## 텐서 속성

In [16]:
tensor_val = torch.rand(3, 4)
print(tensor_val)

# 디바이스 정보 가져오기
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# 외워두기

# 디바이스를 변경하고자 하는 경우
# 텐서의 디바이스를 변경하려면 to() 메서드를 사용할 수 있다. 이 메서드는 새로운 디바이스로 텐서를 이동시킨다.
# Ex) model.to(device)

print(f"Shape of tensor : {tensor_val.shape}")
print(f"Data type of tensor : {tensor_val.dtype}")
print(f"Device tensor is stored on : {tensor_val.device}")

tensor([[0.3331, 0.8170, 0.6360, 0.4615],
        [0.0339, 0.8309, 0.5833, 0.5368],
        [0.7881, 0.0561, 0.8730, 0.8559]])
cpu
Shape of tensor : torch.Size([3, 4])
Data type of tensor : torch.float32
Device tensor is stored on : cpu


In [33]:
# 표준 인덱싱과 슬라이싱
tensor_1 = torch.ones(4,4)
tensor_1[:,3] = 0    # 특정값으로 바꾸기
print(tensor_1)

tensor_2 = torch.ones(4,4)
tensor_2[:,1] = 2
print(tensor_2)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


In [34]:
# 텐서 합치기
# torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다.
t1 = torch.cat([tensor_1, tensor_1, tensor_1], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


In [35]:
t_mult = tensor_1.mul(tensor_2)
print(t_mult)

print(tensor_1 * tensor_2)

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])


In [37]:
# 행렬 곱
print(tensor_2.matmul(tensor_2.T))
print(tensor_2 @ tensor_2.T)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [38]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경
파이토치 텐서의 뷰는 넘파이에서 reshape와 같은 역할<br>
Reshape -> 텐서의 크기를 변경해주는 역할
reshape라는 이름에서 알 수 있듯이, 텐서의 크기(shape)를 변경해주는 역할을 한다.

In [42]:
# 3차원 데이터 생성
t_temp = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t_temp)
print(ft)
print(ft.shape)

# 이제 ft view를 이용해서 2차원 텐서로 변경
print(ft.view([-1, 3]))   # = (?, 3) => 너가 알아서 해라.
# 3의 크기로 바꿔라
print(ft.view([-1, 3]).shape)
# -1의 의미 : 나는 그 값을 모르겠음 파이토치 너가 알아서 해!!
# 두 번째 차원은 길이는 3을 가지도록 하라는 의미

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view() 메서드를 사용하여 텐서의 차원을 변경하면 -> 데이터를 복사하여 새로운 텐서를 생성하고 이 새로운 텐서는 원래 텐서와 메모리를 공유하지 않는다.

In [43]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 스퀴즈
1차원을 제거<br>
스퀴즈는 차원이 1인 경우에는 해당 차언을 제거한다.<br>
실습 3x1 크기를 가지는 2차원 텐서 생성

In [47]:
ft = torch.FloatTensor(([0], [1], [2]))
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## 언스퀴즈
특정 위치에서 1인 차원을 추가한다.

In [46]:
ft_temp = torch.Tensor([0, 1, 2])
print(ft_temp.shape)

torch.Size([3])


In [48]:
# 첫 번째 차원에서 1차원 추가
# 인덱스 0
print(ft_temp.unsqueeze(0))
print(ft_temp.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
print(ft_temp.view(1, -1))
print(ft_temp.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


## 사용자가 정의한 데이터셋

- __init__() 함수는 이미지, csv 읽기, 변환 할당, 데이터 필터링 등과 같은 초기 논리가 발생하는 곳이다.
- __getitem__() : 데이터와 레이블을 반환한다. 이 함수는 dataloader에서 호출된다.
- __len__() : 보유한 샘플 수를 반환

In [3]:
import torch
import os
import glob
from PIL import Image
from torch.utils.data import Dataset, DataLoader

In [5]:
class CustomImageDataset(Dataset) :
    def __init__(self, image_paths, transform = None) :
        # init() 메서드에서는 이미지 파일의 경로와 레이블, 그리고 이미지를 변환하기 위한 transform 인자를 받는다. 이 인자를 통해 데이터셋에 대한 다양한 전처리를 수행할 수 있다.
        self.image_paths = glob.glob(os.path.join(image_paths, "*", "*.jpg"))
        self.transform = transform
        self.label_dict = {"dew" : 0, "fogsmog" : 1, "frost" : 2, "glaze" : 3, "hail" : 4, "lightning" : 5, "rain" : 6, "rainbow" : 7, "rime" : 8, "sandstorm" : 9, "snow" : 10}
        
    def __getitem__(self, index) :
        # getitem() 메서드에서는 주어진 인덱스에 해당하는 이미지 파일을 읽어오고, 해당 이미지 파일의 레이블을 반환한다. 이 메서드에서는 transform 인자를 사용해 이미지를 변환한다.
        image_path = self.image_paths[index]
        image = Image.open(image_path)
        # ./sample_data_01/lightning/2100.jpg
        folder_name = image_path.split("/")
        folder_name = folder_name[2]
        
        label = self.label_dict[folder_name]
        
        # label
        
        if self.transform:
            image = self.transform(image)
            
        return image, label
    
    def __len__(self) :
        # len() 메서드에서는 데이터셋의 크기를 반환한다. 이 경우에는 이미지 파일의 수를 반환한다.
        return len(self.image_paths)
    
# 데이터 경로 ./sample_data_01/이미지 폴더/image.jpg
image_paths = "./sample_data_01/"   # 데이터 폴더 경로 지정
dataset = CustomImageDataset(image_paths, transform=None)

# 디버깅
for i in dataset:
    print("data and label", i)

## Pytorch DataLoader
- Pytorch DataLoader는 데이터셋을 불러와서 모델에 입력으로 사용할 수 있는 형태로 변환해주는 유틸리티 클래스이다. DataLoader는 데이터셋을 불러오고, 데이터를 batch 단위로 분할하여 모델에 전달한다. 이를 통해 모델이 대용량의 데이터셋을 처리할 때 메모리 문제를 최소화할 수 있다.
- DataLoader는 Pytorch에서 제공하는 torch.utils.data 패키지에 포함되어 있으며, 데이터셋과 함께 사용된다. DataLoader는 일반적으로 다음과 같은 인자를 받는다.
- DataLoader는 각 배치를 반복하는 iterator 객체를 반환하며, 각 반복마다 모델에 전달할 입력 데이터와 해당 입력에 대한 레이블 데이터를 반환한다.

In [25]:
# Pytorch DataLoader 간단하게 소개
import torch
import os
import glob
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

def is_grayscale(img):
    return img.mode == 'L'
# 이미지가 Grayscale인지 판단하는 함수



class CustomImageDataset(Dataset) :
    def __init__(self, image_paths, transform = None) :
        self.image_paths = glob.glob(os.path.join(image_paths, "*", "*.jpg"))
        self.transform = transform
        self.label_dict = {"dew" : 0, "fogsmog" : 1, "frost" : 2, "glaze" : 3, "hail" : 4, "lightning" : 5, "rain" : 6, "rainbow" : 7, "rime" : 8, "sandstorm" : 9, "snow" : 10}
        
    def __getitem__(self, index) :
        image_path = self.image_paths[index]
        image = Image.open(image_path).convert("RGB")
        
        # 흑백 이미지 체크 -> RGB 채널 크기가 달라서 오류 발생. 흑백채널은 1 RGB 3이다.
        if not is_grayscale(image) :
            # ./sample_data_01/lightning/2100.jpg
            folder_name = image_path.split("/")
            folder_name = folder_name[2]
            # 라벨 정의
            label = self.label_dict[folder_name]

            # transform -> image aug
            if self.transform :
                image = self.transform(image)
                
            return image, label
        
        else:
            print("흑백 이미지 >> ", image_path)
            
    def __len__(self):
        return len(self.image_paths)
    
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

# 데이터 경로 ./sample_data_01/이미지 폴더/image.jpg
image_paths = "./sample_data_01/"  # 데이터 폴더 경로 지정
# torch 제공하는 transform 라이브러리 사용하여 image aug 정의
dataset = CustomImageDataset(image_paths, transform=transform)

In [27]:
# Dataloader 정의
data_loader = DataLoader(dataset, batch_size=32, shuffle=True)

# DataLoader를 이용하여 데이터 불러오기
for images, labels in data_loader :
    print(images, labels)

IndexError: list index out of range

### Pytorch DataLoader 간단하게 소개 - csv 데이터 이용하여 만들어 보기
- 데이터 소개 - 키와 몸무게 데이터 (키 단위 : 인치 / 몸무게 단위 : 파운드)

In [30]:
# 키는 인치 몸무게는 파운드
class HeightWeightDataset(Dataset) :
    def __init__(self, csv_path):
        self.data = []
        with open(csv_path, 'r', encoding='utf-8') as f:
            next(f)   # 첫 번째 라인은 헤더이므로 제외
            for line in f:
                # print(line)
                _, height, weight = line.strip().split(",")
                height = float(height)
                weight = float(weight)
                convert_to_kg_data = round(self.convert_to_kg(weight), 2)
                convert_to_cm_data = round(self.inch_to_cm(height), 1)
                
                # print(convert_to_kg_data, convert_to_cm_data)
                
                self.data.append([convert_to_cm_data, convert_to_kg_data])
                
    def __getitem__(self, index) :
        data = torch.tensor(self.data[index], dtype=torch.float)
        return data
    
    def __len__(self):
        return len(self.data)
    
    # 파운드 -> Kg 변경하는 함수
    def convert_to_kg(self, weight_lb):
        return weight_lb * 0.453592
    
    # 인치 -> cm 변경 하는 함수
    def inch_to_cm(self, inch):
        return inch * 2.54

In [31]:
dataset = HeightWeightDataset("./hw_200.csv")
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

for batch in dataloader:
    
    # batch[:, 0].unsqueeze(1) 2차원 텐서로 변화됩니다.
    x = batch[:, 0].unsqueeze(1)
    y = batch[:, 1].unsqueeze(1)
    
    print(x, y)

tensor([[170.2000]]) tensor([[58.4300]])
tensor([[176.3000]]) tensor([[58.1800]])
tensor([[175.]]) tensor([[63.6100]])
tensor([[172.3000]]) tensor([[64.0800]])
tensor([[168.6000]]) tensor([[54.5700]])
tensor([[174.8000]]) tensor([[60.1800]])
tensor([[174.2000]]) tensor([[58.]])
tensor([[170.7000]]) tensor([[49.4500]])
tensor([[177.3000]]) tensor([[64.1800]])
tensor([[173.6000]]) tensor([[60.8600]])
tensor([[169.6000]]) tensor([[55.2900]])
tensor([[187.5000]]) tensor([[63.1900]])
tensor([[175.5000]]) tensor([[52.4900]])
tensor([[178.3000]]) tensor([[59.7100]])
tensor([[177.7000]]) tensor([[59.1500]])
tensor([[177.8000]]) tensor([[55.3600]])
tensor([[172.2000]]) tensor([[65.4500]])
tensor([[175.3000]]) tensor([[62.3900]])
tensor([[163.8000]]) tensor([[51.2100]])
tensor([[181.7000]]) tensor([[61.9100]])
tensor([[176.6000]]) tensor([[56.8800]])
tensor([[173.4000]]) tensor([[52.6600]])
tensor([[178.4000]]) tensor([[60.7700]])
tensor([[167.1000]]) tensor([[54.3800]])
tensor([[170.7000]]) ten

## JSON 데이터 이용하여 만들어 보기

In [34]:
import json
from PIL import Image
import torch
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, json_path, transforms=None):
        self.transforms = transforms
        with open(json_path, 'r', encoding='utf-8') as f:
            self.data = json.load(f)
            
    def __getitem__(self, index):
        # 이미지 샘플이 없음 대신 이미지 경로 전달 (원래는 이미지 읽고 이미지를 보내야함)
        # 간단하게 만드는법을 학습하기 위해서 이미지 샘플 제공 x
        print(self.data)
        img_path = self.data[index]['filename']
        img_path = os.path.join("이미지 폴더", img_path)
        # 이미지 읽기
        # img = Image.open(img_path).convert('RGB')
        
        # 바운딩 박스 정보 읽기
        bboxes = self.data[index]['ann']['bboxes']
        labels = self.data[index]['ann']['labels']
        
        # 바운딩 박스 정보를 Tensor로 변환
        bboxes = torch.tensor(bboxes, dtype=torch.float32)
        labels = torch.tensor(labels, dtype = torch.float32)
        
        # 이미지 변환 : 단 주의사항 : 파이토치 제공하는 transforms 박스 위치에 따른 좌표 이동 x
#         if self.transforms is not None:
#             img = self.transforms(img)
        
        return img_path, {'boxes' : bboxes, 'labels' : labels}
    
    def __len__(self) :
        return len(self.data)
    
data = CustomDataset("./test.json", transforms=None)

for image_paths, anno in data:
    pass

[{'filename': 'image_001.jpg', 'width': 1280, 'height': 720, 'ann': {'bboxes': [[10, 10, 50, 50], [100, 100, 200, 200]], 'labels': [0, 1]}}, {'filename': 'image_002.jpg', 'width': 720, 'height': 1280, 'ann': {'bboxes': [[20, 20, 60, 60], [300, 300, 400, 400]], 'labels': [1, 2]}}, {'filename': 'image_003.jpg', 'width': 720, 'height': 1280, 'ann': {'bboxes': [[30, 30, 60, 60], [300, 300, 400, 400]], 'labels': [1, 2]}}, {'filename': 'image_004.jpg', 'width': 720, 'height': 1280, 'ann': {'bboxes': [[10, 10, 60, 60], [300, 300, 400, 400]], 'labels': [1, 2]}}]
[{'filename': 'image_001.jpg', 'width': 1280, 'height': 720, 'ann': {'bboxes': [[10, 10, 50, 50], [100, 100, 200, 200]], 'labels': [0, 1]}}, {'filename': 'image_002.jpg', 'width': 720, 'height': 1280, 'ann': {'bboxes': [[20, 20, 60, 60], [300, 300, 400, 400]], 'labels': [1, 2]}}, {'filename': 'image_003.jpg', 'width': 720, 'height': 1280, 'ann': {'bboxes': [[30, 30, 60, 60], [300, 300, 400, 400]], 'labels': [1, 2]}}, {'filename': 'imag